# Generated by Django 5.1.1 on 2024-09-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_house'),
        ('User', '0003_delete_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_house',
        ),
    ]
