# Generated by Django 5.1.1 on 2024-09-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_house'),
        ('User', '0008_remove_tbl_cart_house_remove_tbl_cart_userid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_house',
        ),
    ]
