# Generated by Django 5.1.1 on 2024-09-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_house'),
        ('User', '0010_delete_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_house',
        ),
    ]
