# Generated by Django 5.1.1 on 2024-09-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_owner',
        ),
    ]
