# Generated by Django 5.1.1 on 2024-09-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_owner',
        ),
    ]
