# Generated by Django 5.1.1 on 2024-09-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0015_tbl_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_house',
        ),
    ]
