# Generated by Django 5.1.1 on 2024-09-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
