# Generated by Django 5.1.1 on 2024-09-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_house'),
        ('Guest', '0001_initial'),
        ('User', '0006_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_amount', models.CharField(max_length=50)),
                ('booking_status', models.CharField(default=0, max_length=10)),
                ('payment_status', models.CharField(default=0, max_length=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
