# Generated by Django 5.1.1 on 2024-09-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='house',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='userid',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
